name = "contact-us-worker-rs"
main = "build/worker/shim.mjs"
compatibility_date = "2025-10-04"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "contact-us-worker-rs"
database_id = "YOUR-DB-ID"

[vars]
ENVIRONMENT = "production"
TURNSTILE_SITEVERIFY_URL = "https://challenges.cloudflare.com/turnstile/v0/siteverify"
ALLOWED_ORIGINS = ""

[env.dev]
[env.dev.vars]
ENVIRONMENT = "dev"
TURNSTILE_SITEVERIFY_URL = "https://challenges.cloudflare.com/turnstile/v0/siteverify"
ALLOWED_ORIGINS = "http://localhost:5173"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "contact-us-worker-rs"
database_id = "YOUR-DB-ID"
preview_database_id = "YOUR-DB-ID"