name: Contact Us CI

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '.github/workflows/**'

jobs:
  contact-us-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "."
          shared-key: "contact-us"
          key: ${{ hashFiles('recipe.json') }}

      - name: Build dependencies
        run: cargo check --target wasm32-unknown-unknown

      - name: Check code formatting
        run: cargo fmt --check

      - name: Run linting
        run: cargo clippy --target wasm32-unknown-unknown -- -D warnings

      - name: Run tests
        run: cargo test

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install Node dependencies
        run: npm ci

      - name: Build worker
        run: npm run build:dev

      - name: Run integration tests
        run: npm test -- --run
